version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: release
          command: yarn add semantic-release || true
